apiVersion: v1
kind: Service
metadata:
  name: upg-loadme-service
spec:
  selector:
    app: upg-loadme  # Select pods labeled with "app: upg-loadme"
  ports:
    - protocol: TCP
      port: 80  # Port exposed on the Service
      targetPort: 8081  # Port that your Node.js application listens on inside the pods
  type: LoadBalancer
